-- Datos iniciales deshabilitados.
-- Este fichero contenía seeds de ejemplo. Se ha limpiado para que la
-- aplicación arranque contra una base de datos vacía y el cliente pueda
-- insertar su propia data. Si desea restaurar los datos de ejemplo,
-- recupere el contenido anterior desde el control de versiones.
